entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:        
        certificates:
          - certFile: "/certs/cert.pem"
            keyFile: "/certs/key.pem"      